#include "fake_shell.h"
#include <Arduino.h>
#include <LittleFS.h>
#include <ArduinoJson.h>
#include <cstring>
#include <cstdlib>

namespace honeyopus {

// ------------ tunables (NEW.md "Safety Rules") ------------
static const uint16_t MAX_COMMANDS_PER_SESSION = 500;
static const uint16_t MAX_CMD_LEN              = 4096;
static const uint16_t MAX_VFS_FILES            = 64;
static const uint32_t MAX_VFILE_SIZE           = 16 * 1024;
static const uint32_t MAX_SLEEP_MS             = 3000;

// ------------ fake static content ------------
static const char* FAKE_PASSWD =
    "root:x:0:0:root:/root:/bin/bash\n"
    "daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin\n"
    "bin:x:2:2:bin:/bin:/usr/sbin/nologin\n"
    "sys:x:3:3:sys:/dev:/usr/sbin/nologin\n"
    "sync:x:4:65534:sync:/bin:/bin/sync\n"
    "man:x:6:12:man:/var/cache/man:/usr/sbin/nologin\n"
    "mail:x:8:8:mail:/var/mail:/usr/sbin/nologin\n"
    "www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin\n"
    "nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin\n"
    "systemd-network:x:100:102:systemd Network Management,,,:/run/systemd/netif:/usr/sbin/nologin\n"
    "syslog:x:102:106::/home/syslog:/usr/sbin/nologin\n"
    "sshd:x:110:65534::/run/sshd:/usr/sbin/nologin\n"
    "ubuntu:x:1000:1000:Ubuntu,,,:/home/ubuntu:/bin/bash\n";

static const char* FAKE_SHADOW =
    "root:!:18000:0:99999:7:::\n"
    "daemon:*:18000:0:99999:7:::\n"
    "ubuntu:!:18000:0:99999:7:::\n";

static const char* FAKE_OS_RELEASE =
    "NAME=\"Ubuntu\"\n"
    "VERSION=\"18.04.6 LTS (Bionic Beaver)\"\n"
    "ID=ubuntu\n"
    "ID_LIKE=debian\n"
    "PRETTY_NAME=\"Ubuntu 18.04.6 LTS\"\n"
    "VERSION_ID=\"18.04\"\n"
    "HOME_URL=\"https://www.ubuntu.com/\"\n"
    "SUPPORT_URL=\"https://help.ubuntu.com/\"\n"
    "BUG_REPORT_URL=\"https://bugs.launchpad.net/ubuntu/\"\n"
    "VERSION_CODENAME=bionic\n"
    "UBUNTU_CODENAME=bionic\n";

static const char* FAKE_ISSUE = "Ubuntu 18.04.6 LTS \\n \\l\n\n";

static const char* FAKE_CPUINFO =
    "processor\t: 0\n"
    "vendor_id\t: GenuineIntel\n"
    "cpu family\t: 6\n"
    "model\t\t: 79\n"
    "model name\t: Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz\n"
    "stepping\t: 1\n"
    "microcode\t: 0xb000038\n"
    "cpu MHz\t\t: 2399.998\n"
    "cache size\t: 35840 KB\n"
    "physical id\t: 0\n"
    "siblings\t: 1\n"
    "core id\t\t: 0\n"
    "cpu cores\t: 1\n"
    "bogomips\t: 4799.99\n"
    "address sizes\t: 46 bits physical, 48 bits virtual\n\n";

static const char* FAKE_MEMINFO =
    "MemTotal:        1009856 kB\n"
    "MemFree:          120432 kB\n"
    "MemAvailable:     704128 kB\n"
    "Buffers:           41216 kB\n"
    "Cached:           512384 kB\n"
    "SwapTotal:             0 kB\n"
    "SwapFree:              0 kB\n";

static const char* FAKE_MOUNTS_PROC =
    "sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0\n"
    "proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0\n"
    "udev /dev devtmpfs rw,nosuid,relatime,size=494056k,nr_inodes=123514,mode=755 0 0\n"
    "/dev/vda1 / ext4 rw,relatime,errors=remount-ro,data=ordered 0 0\n"
    "tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=101000k,mode=755 0 0\n";

static const char* FAKE_HOSTS =
    "127.0.0.1 localhost\n"
    "127.0.1.1 ubuntu\n\n"
    "# The following lines are desirable for IPv6 capable hosts\n"
    "::1     ip6-localhost ip6-loopback\n"
    "fe00::0 ip6-localnet\n"
    "ff00::0 ip6-mcastprefix\n"
    "ff02::1 ip6-allnodes\n"
    "ff02::2 ip6-allrouters\n";

static const char* FAKE_RESOLV =
    "# Generated by NetworkManager\n"
    "nameserver 8.8.8.8\n"
    "nameserver 1.1.1.1\n";

static const char* FAKE_UNAME_A =
    "Linux ubuntu 4.15.0-142-generic #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux";

static const char* FAKE_UPTIME_PROC = "1234567.89 1234000.00\n";

// ----- helpers -----
static String trim(const String& s) {
    int a=0,b=s.length();
    while(a<b && isspace((unsigned char)s[a])) ++a;
    while(b>a && isspace((unsigned char)s[b-1])) --b;
    return s.substring(a,b);
}
static bool startsWith(const String& s, const char* p) { return s.startsWith(p); }
static bool endsWith(const String& s, const char* p) {
    size_t pl=strlen(p); return s.length()>=pl && s.endsWith(p);
}
static String join(const std::vector<String>& v, char sep, size_t from=0) {
    String r;
    for (size_t i=from;i<v.size();++i) { if(i>from) r+=sep; r+=v[i]; }
    return r;
}
static long toLongOr(const String& s, long d) {
    char* e=nullptr; long v=strtol(s.c_str(),&e,10);
    if (!e || *e!='\0') return d; return v;
}
static String pad(const String& s, int w) {
    String r=s; while ((int)r.length()<w) r+=' '; return r;
}

// ===================== begin / motd / prompt =====================

void FakeShell::begin(const String& user, const String& host) {
    user_ = user;
    host_ = host.length() ? host : String("ubuntu");
    cwd_  = (user_=="root") ? "/root" : ("/home/"+user_);
    commands_=0; exit_=false; cap_hit_=false;
    last_status_ok_=true;
    files_.clear(); procs_.clear(); history_.clear(); env_.clear();
    crontab_="";

    env_.push_back({"HOME", cwd_});
    env_.push_back({"USER", user_});
    env_.push_back({"LOGNAME", user_});
    env_.push_back({"SHELL", "/bin/bash"});
    env_.push_back({"PATH", "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"});
    env_.push_back({"PWD", cwd_});
    env_.push_back({"LANG", "C.UTF-8"});
    env_.push_back({"TERM", "xterm-256color"});
    env_.push_back({"HOSTNAME", host_});
    env_.push_back({"MAIL", "/var/mail/"+user_});

    // prepopulate a minimal process table
    procs_.push_back({1, "root", "?", "/sbin/init"});
    procs_.push_back({412, "root", "?", "/lib/systemd/systemd-journald"});
    procs_.push_back({501, "root", "?", "/usr/sbin/sshd -D"});
    procs_.push_back({502, "root", "?", "/usr/sbin/cron -f"});
    procs_.push_back({601, "syslog", "?", "/usr/sbin/rsyslogd -n"});
    procs_.push_back({743, "root", "tty1", "-bash"});
    procs_.push_back({999, "root", "pts/0", "-bash"});
}

void FakeShell::setSessionInfo(uint32_t session_id, const String& source_ip,
                               uint16_t source_port, const String& protocol,
                               const String& events_path) {
    session_id_=session_id; src_ip_=source_ip; src_port_=source_port;
    proto_=protocol; events_path_=events_path;
}

String FakeShell::motd() const {
    String s;
    s += "Welcome to Ubuntu 18.04.6 LTS (GNU/Linux 4.15.0-142-generic x86_64)\r\n\r\n";
    s += " * Documentation:  https://help.ubuntu.com\r\n";
    s += " * Management:     https://landscape.canonical.com\r\n";
    s += " * Support:        https://ubuntu.com/advantage\r\n\r\n";
    s += "  System information as of " + String(millis()/1000) + "\r\n\r\n";
    s += "  System load:  0.08              Processes:           98\r\n";
    s += "  Usage of /:   23.4% of 19.56GB  Users logged in:     0\r\n";
    s += "  Memory usage: 28%               IP address for eth0: 10.0.0.42\r\n";
    s += "  Swap usage:   0%\r\n\r\n";
    s += "0 packages can be updated.\r\n";
    s += "0 updates are security updates.\r\n\r\n";
    s += "Last login: Mon Sep  4 09:14:21 2023 from 192.168.1.5\r\n";
    return s;
}

String FakeShell::prompt() const {
    String p = user_ + "@" + host_ + ":";
    String c = cwd_;
    String home = (user_=="root") ? "/root" : ("/home/"+user_);
    if (c == home) p += "~";
    else if (c.startsWith(home+"/")) p += "~"+c.substring(home.length());
    else p += c;
    p += (user_=="root") ? "# " : "$ ";
    return p;
}

// ===================== parsing =====================

String FakeShell::basename_(const String& p) {
    int i = p.lastIndexOf('/');
    return (i<0) ? p : p.substring(i+1);
}

String FakeShell::normalizeExe_(const String& exe) {
    String b = basename_(exe);
    // BusyBox-style: strip "busybox " prefix or busybox alias names
    if (b == "busybox") return "busybox";
    return b;
}

// Tokenize one segment with quote awareness; supports VAR=val prefixes & redirs.
static void tokenize(const String& src, std::vector<String>& out) {
    String cur;
    bool inS=false, inD=false;
    bool have=false;
    for (size_t i=0;i<src.length();++i) {
        char c = src[i];
        if (!inS && c=='\\' && i+1<src.length()) { cur+=src[i+1]; ++i; have=true; continue; }
        if (!inS && c=='"') { inD=!inD; have=true; continue; }
        if (!inD && c=='\'') { inS=!inS; have=true; continue; }
        if (!inS && !inD && (c==' '||c=='\t')) {
            if (have) { out.push_back(cur); cur=""; have=false; }
            continue;
        }
        cur+=c; have=true;
    }
    if (have) out.push_back(cur);
}

bool FakeShell::parseCmd_(const String& src, Cmd& out) {
    String s = trim(src);
    if (!s.length()) return false;

    // background marker at end
    if (s.endsWith("&")) {
        // but not "&&" or "&>" — those handled elsewhere
        if (!s.endsWith("&&") && !s.endsWith("&>")) {
            out.background = true;
            s = trim(s.substring(0, s.length()-1));
        }
    }

    std::vector<String> tok;
    tokenize(s, tok);
    if (tok.empty()) return false;

    // Strip env prefix VAR=val ...
    size_t k=0;
    while (k<tok.size()) {
        const String& t = tok[k];
        int eq = t.indexOf('=');
        if (eq>0) {
            bool ok=true;
            for (int i=0;i<eq;++i) {
                char ch=t[i];
                if (!(isalnum((unsigned char)ch)||ch=='_')) { ok=false; break; }
            }
            if (ok) {
                out.env_prefix.push_back({t.substring(0,eq), t.substring(eq+1)});
                ++k; continue;
            }
        }
        break;
    }
    if (k>=tok.size()) return false;

    // Walk tokens for redirections
    std::vector<String> argv;
    for (; k<tok.size(); ++k) {
        const String& t = tok[k];
        if (t == ">" || t == "1>") {
            if (k+1<tok.size()) {
                if (tok[k+1]=="/dev/null") out.redirect_null=true;
                else out.redirect_stdout = tok[k+1];
                ++k;
            }
            continue;
        }
        if (t == ">>") {
            if (k+1<tok.size()) { out.redirect_append = tok[k+1]; ++k; }
            continue;
        }
        if (t == "2>") {
            if (k+1<tok.size()) {
                if (tok[k+1]=="/dev/null") out.redirect_stderr_null=true;
                ++k;
            }
            continue;
        }
        if (t == "&>" || t == "2>&1") {
            if (t == "&>" && k+1<tok.size() && tok[k+1]=="/dev/null") {
                out.redirect_null=true; out.redirect_stderr_null=true; ++k;
            } else if (t=="&>") {
                if (k+1<tok.size()) { out.redirect_stdout=tok[k+1]; ++k; }
            }
            continue;
        }
        // 2>&1 inline
        if (t.endsWith("2>&1")) continue;
        argv.push_back(t);
    }
    if (argv.empty()) return false;

    out.argv = argv;
    out.exe  = normalizeExe_(argv[0]);
    out.raw  = s;
    return true;
}

int FakeShell::splitChain_(const String& line, std::vector<CmdNode>& out) {
    // Split on ; && || | with quote awareness.
    String cur;
    bool inS=false, inD=false;
    auto flush = [&](Sep sep){
        Cmd c;
        if (parseCmd_(cur, c)) {
            CmdNode n; n.cmd = c; n.follow = sep;
            out.push_back(n);
        }
        cur="";
    };
    for (size_t i=0;i<line.length();++i) {
        char ch=line[i];
        if (!inS && ch=='\\' && i+1<line.length()) { cur+=ch; cur+=line[i+1]; ++i; continue; }
        if (!inS && ch=='"') { inD=!inD; cur+=ch; continue; }
        if (!inD && ch=='\'') { inS=!inS; cur+=ch; continue; }
        if (!inS && !inD) {
            if (ch=='&' && i+1<line.length() && line[i+1]=='&') { flush(SEP_AND); ++i; continue; }
            if (ch=='|' && i+1<line.length() && line[i+1]=='|') { flush(SEP_OR);  ++i; continue; }
            if (ch=='|') { flush(SEP_PIPE); continue; }
            if (ch==';') { flush(SEP_SEMI); continue; }
        }
        cur+=ch;
    }
    if (trim(cur).length()) flush(SEP_NONE);
    return (int)out.size();
}

// ===================== path / vfs =====================

String FakeShell::resolvePath_(const String& p) const {
    if (!p.length()) return cwd_;
    String s = p;
    if (s == "~") s = (user_=="root") ? "/root" : ("/home/"+user_);
    else if (s.startsWith("~/")) s = ((user_=="root") ? "/root" : ("/home/"+user_)) + s.substring(1);
    String abs = s.startsWith("/") ? s : (cwd_=="/" ? "/"+s : cwd_+"/"+s);

    // normalize . and ..
    std::vector<String> parts;
    int i=0;
    while (i < (int)abs.length()) {
        int j = abs.indexOf('/', i);
        if (j<0) j = abs.length();
        String seg = abs.substring(i, j);
        if (seg.length() && seg != ".") {
            if (seg == "..") { if (!parts.empty()) parts.pop_back(); }
            else parts.push_back(seg);
        }
        i = j+1;
    }
    String r="";
    for (auto& x : parts) { r += "/"; r += x; }
    if (!r.length()) r = "/";
    return r;
}

bool FakeShell::isWritableDir_(const String& dir) {
    return dir=="/tmp" || dir.startsWith("/tmp/") ||
           dir=="/var/tmp" || dir.startsWith("/var/tmp/") ||
           dir=="/dev/shm" || dir.startsWith("/dev/shm/") ||
           dir=="/root" || dir.startsWith("/root/") ||
           dir.startsWith("/home/") || dir=="/var/run" || dir.startsWith("/var/run/");
}

VirtualFile* FakeShell::findFile_(const String& abs) {
    for (auto& f : files_) if (f.path == abs) return &f;
    return nullptr;
}
const VirtualFile* FakeShell::findFile_(const String& abs) const {
    for (auto& f : files_) if (f.path == abs) return &f;
    return nullptr;
}
bool FakeShell::fileExists_(const String& abs) const {
    if (findFile_(abs)) return true;
    // baked-in real-ish files
    if (abs=="/etc/passwd"||abs=="/etc/shadow"||abs=="/etc/os-release"||
        abs=="/etc/issue"||abs=="/etc/hostname"||abs=="/etc/hosts"||
        abs=="/etc/resolv.conf"||abs=="/proc/cpuinfo"||abs=="/proc/meminfo"||
        abs=="/proc/mounts"||abs=="/proc/version"||abs=="/proc/uptime") return true;
    return false;
}
bool FakeShell::isDir_(const String& abs) const {
    auto* f = findFile_(abs);
    if (f) return f->is_dir;
    if (abs=="/"||abs=="/tmp"||abs=="/var"||abs=="/var/tmp"||abs=="/var/log"||
        abs=="/var/run"||abs=="/etc"||abs=="/root"||abs=="/home"||abs=="/dev"||
        abs=="/dev/shm"||abs=="/proc"||abs=="/sys"||abs=="/usr"||abs=="/usr/bin"||
        abs=="/usr/sbin"||abs=="/usr/local"||abs=="/bin"||abs=="/sbin"||abs=="/lib"||
        abs=="/opt"||abs=="/mnt"||abs.startsWith("/home/")) return true;
    // Common home subdirs
    if (abs=="/root/.ssh"||abs=="/root/.cache") return true;
    if (abs.startsWith("/home/") &&
        (abs.endsWith("/.ssh")||abs.endsWith("/.cache"))) return true;
    // /etc subdirs commonly traversed
    if (abs=="/etc/ssh"||abs=="/etc/systemd"||abs=="/etc/apt"||
        abs=="/etc/cron.d"||abs=="/etc/cron.hourly"||abs=="/etc/cron.daily") return true;
    return false;
}

VirtualFile* FakeShell::createFile_(const String& abs, const String& created_by) {
    if (auto* f = findFile_(abs)) return f;
    if (files_.size() >= MAX_VFS_FILES) { cap_hit_ = true; return nullptr; }
    VirtualFile f;
    f.path=abs; f.created_by=created_by; f.created_ms=millis(); f.mtime_ms=millis();
    files_.push_back(f);
    return &files_.back();
}

// ===================== payload helpers =====================

String FakeShell::guessArch_(const String& s) {
    String x = s; x.toLowerCase();
    if (x.indexOf("x86_64")>=0||x.indexOf("amd64")>=0) return "x86_64";
    if (x.indexOf("i686")>=0||x.indexOf("i386")>=0||x.indexOf(".x86")>=0) return "x86";
    if (x.indexOf("aarch64")>=0||x.indexOf("arm64")>=0) return "aarch64";
    if (x.indexOf("armv7")>=0||x.indexOf("arm7")>=0) return "armv7";
    if (x.indexOf("armv6")>=0||x.indexOf("arm6")>=0) return "armv6";
    if (x.indexOf("arm")>=0) return "arm";
    if (x.indexOf("mips")>=0) return "mips";
    if (x.indexOf("mipsel")>=0) return "mipsel";
    if (x.indexOf("ppc")>=0||x.indexOf("powerpc")>=0) return "ppc";
    if (x.indexOf("sh4")>=0) return "sh4";
    if (x.indexOf("spc")>=0||x.indexOf("sparc")>=0) return "sparc";
    return "x86_64";
}

String FakeShell::guessProfile_(const String& url, const String& name) {
    String u = url; u.toLowerCase();
    String n = name; n.toLowerCase();
    if (u.indexOf("xmrig")>=0||n.indexOf("xmrig")>=0||n.indexOf("miner")>=0||
        u.indexOf("monero")>=0||u.indexOf("cpuminer")>=0) return "crypto_miner";
    if (n.indexOf("mirai")>=0||u.indexOf("mirai")>=0||
        n=="x86"||n=="arm"||n=="arm5"||n=="arm6"||n=="arm7"||n=="mips"||
        n=="mipsel"||n=="ppc"||n=="sh4"||n=="spc"||n=="m68k") return "mirai_like_bot";
    if (n.indexOf("kinsing")>=0||u.indexOf("kinsing")>=0) return "kinsing";
    if (n.indexOf("tsunami")>=0||u.indexOf("tsunami")>=0) return "tsunami";
    if (n.indexOf("perl")>=0||n.endsWith(".pl")) return "perlbot";
    if (n.endsWith(".sh")) return "shell_dropper";
    return "generic_bot";
}

void FakeShell::detectReverseShell_(const Cmd& c, String& /*out*/) {
    String r = c.raw; String low = r; low.toLowerCase();
    bool hit=false; String tech;
    if (low.indexOf("bash -i")>=0 && low.indexOf("/dev/tcp/")>=0) { hit=true; tech="bash_dev_tcp"; }
    else if (low.indexOf("/dev/tcp/")>=0) { hit=true; tech="dev_tcp"; }
    else if ((low.indexOf("nc ")>=0||low.indexOf("ncat ")>=0) && (low.indexOf(" -e")>=0||low.indexOf("/bin/sh")>=0||low.indexOf("/bin/bash")>=0)) { hit=true; tech="nc_e"; }
    else if (low.indexOf("python")>=0 && low.indexOf("socket.socket")>=0 && low.indexOf("dup2")>=0) { hit=true; tech="python_socket"; }
    else if (low.indexOf("perl")>=0 && low.indexOf("socket")>=0 && low.indexOf("exec")>=0) { hit=true; tech="perl_socket"; }
    else if (low.indexOf("php")>=0 && low.indexOf("fsockopen")>=0) { hit=true; tech="php_fsockopen"; }
    else if (low.indexOf("socat")>=0 && low.indexOf("exec:")>=0) { hit=true; tech="socat_exec"; }
    else if (low.indexOf("mkfifo")>=0 && low.indexOf("nc ")>=0) { hit=true; tech="mkfifo_nc"; }
    if (hit) {
        StaticJsonDocument<384> d;
        d["technique"]=tech;
        d["raw"]=r.substring(0, min((unsigned)r.length(), 480u));
        String body; serializeJson(d, body);
        logEvent_("reverse_shell_attempt", body);
    }
}

// ===================== logging =====================

void FakeShell::logEvent_(const String& type, const String& json_body) {
    if (!events_path_.length()) return;
    StaticJsonDocument<128> head;
    head["ts"]   = (uint32_t) (millis()/1000);
    head["session"] = session_id_;
    head["ip"]   = src_ip_;
    head["port"] = src_port_;
    head["proto"]= proto_;
    head["type"] = type;
    String h; serializeJson(head, h);
    // splice body fields into head
    String line = h;
    if (json_body.length() && json_body[0]=='{') {
        // remove trailing '}' from head, prepend ',' + body inner
        line.remove(line.length()-1);
        if (json_body.length()>2) {
            line += ",";
            line += json_body.substring(1, json_body.length()-1);
        }
        line += "}";
    }
    line += "\n";
    File f = LittleFS.open(events_path_.c_str(), "a");
    if (!f) return;
    f.print(line);
    f.close();
}

void FakeShell::logCommand_(const String& raw, const std::vector<CmdNode>& chain) {
    StaticJsonDocument<512> d;
    d["raw"] = raw.substring(0, min((unsigned)raw.length(), 480u));
    JsonArray a = d["cmds"].to<JsonArray>();
    for (auto& n : chain) {
        JsonObject o = a.add<JsonObject>();
        o["exe"] = n.cmd.exe;
        JsonArray args = o["argv"].to<JsonArray>();
        for (auto& x : n.cmd.argv) args.add(x);
        switch (n.follow) {
            case SEP_AND:  o["sep"]="&&"; break;
            case SEP_OR:   o["sep"]="||"; break;
            case SEP_PIPE: o["sep"]="|"; break;
            case SEP_SEMI: o["sep"]=";"; break;
            default: break;
        }
    }
    String b; serializeJson(d, b);
    logEvent_("command", b);
}

// ===================== execute =====================

String FakeShell::execute(const String& line) {
    if (cap_hit_) return "";
    if (line.length() > MAX_CMD_LEN) { cap_hit_=true; return ""; }
    String s = trim(line);
    if (!s.length()) return "";
    if (++commands_ > MAX_COMMANDS_PER_SESSION) { cap_hit_=true; return ""; }
    {
        uint32_t now = millis();
        if (first_cmd_ms_ == 0) first_cmd_ms_ = now;
        last_cmd_ms_ = now;
    }
    history_.push_back(s);
    if (history_.size() > 256) history_.erase(history_.begin());
    String out = runChain_(s);
    // Normalize newlines for raw telnet/ssh terminals: bare \n -> \r\n
    String norm; norm.reserve(out.length() + 16);
    char prev = 0;
    for (size_t i = 0; i < out.length(); ++i) {
        char c = out[i];
        if (c == '\n' && prev != '\r') norm += '\r';
        norm += c;
        prev = c;
    }
    return norm;
}

String FakeShell::runChain_(const String& raw) {
    std::vector<CmdNode> chain;
    splitChain_(raw, chain);
    if (chain.empty()) return "";
    logCommand_(raw, chain);

    String out;
    bool prev_ok = true;
    Sep prev_sep = SEP_NONE;
    for (size_t i=0;i<chain.size();++i) {
        CmdNode& n = chain[i];
        bool run = true;
        if (i>0) {
            if (prev_sep == SEP_AND && !prev_ok) run=false;
            else if (prev_sep == SEP_OR && prev_ok) run=false;
        }
        if (run) {
            // detect reverse shell on each segment first
            detectReverseShell_(n.cmd, out);
            String r = runWithRedirects_(n.cmd);
            out += r;
            prev_ok = last_status_ok_;
        }
        prev_sep = n.follow;
        if (exit_ || cap_hit_) break;
    }
    return out;
}

String FakeShell::runWithRedirects_(Cmd& c) {
    String r = runOne_(c);
    // honor redirect_null/stderr_null and to-file by writing into VFS
    if (c.redirect_null) return "";
    if (c.redirect_stdout.length() || c.redirect_append.length()) {
        String tgt = c.redirect_stdout.length() ? c.redirect_stdout : c.redirect_append;
        String abs = resolvePath_(tgt);
        if (isWritableDir_(abs.substring(0, abs.lastIndexOf('/')+1))) {
            VirtualFile* vf = createFile_(abs, "redirect");
            if (vf) {
                if (c.redirect_append.length()) vf->content += r;
                else vf->content = r;
                if (vf->content.length() > MAX_VFILE_SIZE)
                    vf->content.remove(MAX_VFILE_SIZE);
                vf->size = vf->content.length();
                vf->mtime_ms = millis();
                // detect authorized_keys persistence
                if (abs.endsWith("/.ssh/authorized_keys")) {
                    StaticJsonDocument<256> d;
                    d["path"]=abs;
                    d["bytes"]=(uint32_t)r.length();
                    String b; serializeJson(d, b);
                    logEvent_("authorized_key_added", b);
                }
            }
        }
        return "";
    }
    return r;
}

// ===================== command dispatch =====================

String FakeShell::runOne_(Cmd& c) {
    last_status_ok_ = true;
    const String& e = c.exe;

    // BusyBox aliasing: "busybox <cmd> ..." -> shift. If <cmd> isn't a real
    // applet we *must* mimic BusyBox's "<applet>: applet not found" output —
    // Mirai/Gafgyt droppers probe exactly with `/bin/busybox <RANDOMSTRING>`
    // and treat the bash-style "command not found" as a honeypot tell.
    if (e == "busybox") {
        if (c.argv.size() < 2) {
            // Bare `busybox` — print a stub banner like real busybox does.
            return F("BusyBox v1.30.1 (2020-12-23 15:49:40 UTC) multi-call binary.\n"
                     "BusyBox is copyrighted by many authors between 1998-2015.\n"
                     "Licensed under GPLv2. See source distribution for detailed\n"
                     "copyright notices.\n\n"
                     "Usage: busybox [function [arguments]...]\n");
        }
        String applet = c.argv[1];
        c.argv.erase(c.argv.begin());
        c.exe = normalizeExe_(c.argv[0]);
        String r = runOne_(c);
        // If the inner dispatch fell through to the bash not-found message,
        // rewrite it as the BusyBox applet-not-found line. last_status_ok_
        // remains false either way.
        if (!last_status_ok_ && r.startsWith("-bash:")) {
            return applet + ": applet not found\n";
        }
        return r;
    }

    // path execution: ./x, /tmp/x, etc.
    if (c.argv[0].startsWith("./") || c.argv[0].startsWith("/")) {
        if (c.argv[0].endsWith(".sh") || c.argv[0].startsWith("/tmp/") ||
            c.argv[0].startsWith("/var/tmp/") || c.argv[0].startsWith("/dev/shm/") ||
            c.argv[0].startsWith("./")) {
            return cmdExecute_(c);
        }
    }

    if (e=="exit"||e=="logout"||e=="quit") { exit_=true; return ""; }
    if (e=="echo") return cmdEcho_(c);
    if (e=="ls"||e=="dir") return cmdLs_(c);
    if (e=="cd") return cmdCd_(c);
    if (e=="pwd") return cwd_+"\n";
    if (e=="whoami") return user_+"\n";
    if (e=="hostname") return host_+"\n";
    if (e=="uname") return cmdUname_(c);
    if (e=="id") return cmdId_(c);
    if (e=="cat") return cmdCat_(c);
    if (e=="head") return cmdHead_(c, false);
    if (e=="tail") return cmdHead_(c, true);
    if (e=="grep"||e=="egrep"||e=="fgrep") return cmdGrep_(c);
    if (e=="wc") return cmdWc_(c);
    if (e=="base64") return cmdBase64_(c);
    if (e=="ps") return cmdPs_(c);
    if (e=="netstat") return cmdNetstat_(c);
    if (e=="ss") return cmdSs_(c);
    if (e=="ifconfig") return cmdIfconfig_(c);
    if (e=="ip") return cmdIp_(c);
    if (e=="route") return cmdRoute_(c);
    if (e=="df") return cmdDf_(c);
    if (e=="free") return cmdFree_(c);
    if (e=="uptime") return cmdUptime_(c);
    if (e=="w"||e=="who") return cmdW_(c);
    if (e=="last") return cmdLast_(c);
    if (e=="mount") return cmdMount_(c);
    if (e=="lscpu") return cmdLscpu_(c);
    if (e=="env"||e=="printenv") return cmdEnv_(c);
    if (e=="export"||e=="set") return cmdExport_(c);
    if (e=="history") return cmdHistory_(c);
    if (e=="wget") return cmdWget_(c);
    if (e=="curl") return cmdCurl_(c);
    if (e=="chmod") return cmdChmod_(c);
    if (e=="chown"||e=="chgrp") return cmdChown_(c);
    if (e=="rm") return cmdRm_(c);
    if (e=="mkdir") return cmdMkdir_(c);
    if (e=="rmdir") return ""; // silent
    if (e=="touch") return cmdTouch_(c);
    if (e=="mv") return cmdMv_(c);
    if (e=="cp") return cmdCp_(c);
    if (e=="which") return cmdWhich_(c);
    if (e=="whereis"||e=="type") return cmdWhereis_(c);
    if (e=="sleep") return cmdSleep_(c);
    if (e=="apt"||e=="apt-get"||e=="aptitude") return cmdApt_(c);
    if (e=="dpkg") return cmdDpkg_(c);
    if (e=="pip"||e=="pip2"||e=="pip3") return cmdPip_(c);
    if (e=="crontab") return cmdCrontab_(c);
    if (e=="systemctl") return cmdSystemctl_(c);
    if (e=="service") return cmdService_(c);
    if (e=="kill"||e=="killall"||e=="pkill") return cmdKill_(c, e);
    if (e=="nc"||e=="ncat") return cmdNc_(c);
    if (e=="ping"||e=="ping6") return cmdPing_(c);
    if (e=="iptables") return cmdIptables_(c);
    if (e=="ufw") return cmdUfw_(c);
    if (e=="sh"||e=="bash"||e=="ash"||e=="dash"||e=="zsh") return cmdShEval_(c);
    if (e=="python"||e=="python2"||e=="python3"||e=="perl"||e=="php"||
        e=="ruby"||e=="lua") return cmdInterp_(c);
    if (e=="nohup"||e=="setsid"||e=="timeout"||e=="screen"||e=="tmux") {
        if (c.argv.size()>=2) {
            // shift one or two leading wrappers
            String first=c.argv[1];
            c.argv.erase(c.argv.begin());
            if ((e=="timeout") && c.argv.size()>=2) {
                // timeout DURATION CMD ...
                c.argv.erase(c.argv.begin());
            }
            if (!c.argv.empty()) {
                c.exe = normalizeExe_(c.argv[0]);
                return runOne_(c);
            }
        }
        return "";
    }
    if (e=="reboot"||e=="shutdown"||e=="halt"||e=="poweroff") {
        last_status_ok_=false;
        return e+": Failed to set wall message: Operation not permitted\nFailed to reboot system via logind: Access denied\nFailed to open /dev/initctl: Permission denied\n";
    }
    if (e=="clear") return "\x1b[H\x1b[2J";
    if (e==":"||e=="true") return "";
    if (e=="false") { last_status_ok_=false; return ""; }

    // not found
    last_status_ok_ = false;
    return "-bash: " + c.argv[0] + ": command not found\n";
}

// ===================== individual commands =====================

String FakeShell::cmdEcho_(Cmd& c) {
    bool n=false; size_t i=1;
    while (i<c.argv.size() && c.argv[i].length()>1 && c.argv[i][0]=='-') {
        if (c.argv[i]=="-n") { n=true; ++i; continue; }
        if (c.argv[i]=="-e"||c.argv[i]=="-E") { ++i; continue; }
        break;
    }
    String r;
    for (size_t j=i;j<c.argv.size();++j) { if (j>i) r+=' '; r+=c.argv[j]; }
    if (!n) r+='\n';
    return r;
}

String FakeShell::cmdLs_(Cmd& c) {
    bool longf=false, all=false;
    String target;
    for (size_t i=1;i<c.argv.size();++i) {
        const String& a=c.argv[i];
        if (a.startsWith("-")) {
            if (a.indexOf('l')>=0) longf=true;
            if (a.indexOf('a')>=0) all=true;
        } else target=a;
    }
    String dir = resolvePath_(target.length()?target:cwd_);
    String out;
    std::vector<String> emitted;

    auto emit = [&](const String& name, bool is_dir, uint32_t sz){
        for (auto& n : emitted) if (n == name) return;
        emitted.push_back(name);
        if (longf) {
            String mode = is_dir ? "drwxr-xr-x" : "-rw-r--r--";
            out += mode; out += " 1 root root ";
            String ssz = String(sz);
            while (ssz.length()<6) ssz=" "+ssz;
            out += ssz; out += " Sep  4 09:14 "; out += name; out += "\n";
        } else { out += name; out += "  "; }
    };

    String home = (user_=="root") ? "/root" : ("/home/"+user_);
    if (dir == home) {
        if (all) { emit(".", true, 4096); emit("..", true, 4096); emit(".bash_history", false, 1024); emit(".bashrc", false, 3771); emit(".profile", false, 807); }
        emit(".cache", true, 4096);
        emit(".ssh", true, 4096);
    } else if (dir == home + "/.ssh") {
        if (all) { emit(".", true, 4096); emit("..", true, 4096); }
        emit("authorized_keys", false, 0);
        emit("known_hosts", false, 1776);
    } else if (dir == home + "/.cache") {
        if (all) { emit(".", true, 4096); emit("..", true, 4096); }
        emit("motd.legal-displayed", false, 0);
    } else if (dir == "/") {
        const char* roots[]={"bin","boot","dev","etc","home","lib","media","mnt","opt","proc","root","run","sbin","srv","sys","tmp","usr","var",nullptr};
        for (int j=0;roots[j];++j) emit(roots[j], true, 4096);
    } else if (dir == "/etc") {
        const char* es[]={"passwd","shadow","hostname","hosts","resolv.conf","os-release","issue","crontab","cron.d","cron.hourly","cron.daily","ssh","systemd","apt",nullptr};
        for (int j=0;es[j];++j) emit(es[j], (j>=8), j<8?(uint32_t)512:4096);
    } else if (dir == "/tmp" || dir == "/var/tmp" || dir == "/dev/shm") {
        if (all) { emit(".", true, 4096); emit("..", true, 4096); }
    } else if (!isDir_(dir)) {
        last_status_ok_=false;
        return "ls: cannot access '" + (target.length()?target:dir) + "': No such file or directory\n";
    } else {
        if (all) { emit(".", true, 4096); emit("..", true, 4096); }
    }
    // Always overlay any VFS files that live directly under `dir` — files the
    // attacker just `touch`ed or redirected into. Without this, attacker writes
    // appeared to vanish because the static directory branches above never
    // consulted the VFS.
    {
        String prefix = (dir == "/") ? String("/") : (dir + "/");
        size_t base = (dir == "/") ? 1 : (dir.length() + 1);
        for (auto& f : files_) {
            if (f.path.startsWith(prefix) && f.path.indexOf('/', base) < 0) {
                emit(basename_(f.path), f.is_dir, f.size);
            }
        }
    }
    if (!longf && out.length() && !out.endsWith("\n")) { out=trim(out); out+="\n"; }
    return out;
}

String FakeShell::cmdCd_(Cmd& c) {
    String t = (c.argv.size()<2) ? "~" : c.argv[1];
    String abs = resolvePath_(t);
    if (!isDir_(abs)) {
        last_status_ok_=false;
        return "-bash: cd: "+t+": No such file or directory\n";
    }
    cwd_ = abs;
    for (auto& kv : env_) if (kv.first=="PWD") kv.second = cwd_;
    return "";
}

String FakeShell::passwdFile_() const { return FAKE_PASSWD; }

String FakeShell::cmdCat_(Cmd& c) {
    if (c.argv.size()<2) return "";
    String out;
    for (size_t i=1;i<c.argv.size();++i) {
        const String& arg=c.argv[i];
        if (arg.startsWith("-")) continue;
        String abs = resolvePath_(arg);
        if (abs=="/etc/passwd") { out += FAKE_PASSWD; continue; }
        if (abs=="/etc/shadow") {
            if (user_!="root") { last_status_ok_=false; out += "cat: /etc/shadow: Permission denied\n"; continue; }
            out += FAKE_SHADOW; continue;
        }
        if (abs=="/etc/os-release") { out += FAKE_OS_RELEASE; continue; }
        if (abs=="/etc/issue")      { out += FAKE_ISSUE; continue; }
        if (abs=="/etc/hostname")   { out += host_; out += "\n"; continue; }
        if (abs=="/etc/hosts")      { out += FAKE_HOSTS; continue; }
        if (abs=="/etc/resolv.conf"){ out += FAKE_RESOLV; continue; }
        if (abs=="/proc/cpuinfo")   { out += FAKE_CPUINFO; continue; }
        if (abs=="/proc/meminfo")   { out += FAKE_MEMINFO; continue; }
        if (abs=="/proc/mounts")    { out += FAKE_MOUNTS_PROC; continue; }
        if (abs=="/proc/uptime")    { out += FAKE_UPTIME_PROC; continue; }
        if (abs=="/proc/version")   { out += "Linux version 4.15.0-142-generic (buildd@lcy01-amd64-006) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021\n"; continue; }
        auto* vf = findFile_(abs);
        if (vf) { out += vf->content; continue; }
        // Stubbed home-dir files: list-empty rather than 404 so attackers see consistency
        String home = (user_=="root") ? "/root" : ("/home/"+user_);
        if (abs == home + "/.ssh/authorized_keys") continue; // empty file
        if (abs == home + "/.ssh/known_hosts") {
            out += "|1|abc123def456=|xyz789==|ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQ...\n";
            continue;
        }
        if (abs == home + "/.bash_history") {
            out += "ls\ncd\nuname -a\nps aux\nexit\n"; continue;
        }
        if (abs == home + "/.bashrc" || abs == home + "/.profile") {
            out += "# ~/.bashrc: executed by bash(1) for non-login shells.\n"
                   "[ -z \"$PS1\" ] && return\nexport PATH=$PATH:/usr/local/bin\n";
            continue;
        }
        if (abs == home + "/.cache/motd.legal-displayed") continue;
        last_status_ok_=false;
        out += "cat: " + arg + ": No such file or directory\n";
    }
    return out;
}

String FakeShell::cmdHead_(Cmd& c, bool tail) {
    int n=10; size_t i=1;
    while (i<c.argv.size() && c.argv[i].startsWith("-")) {
        if (c.argv[i]=="-n" && i+1<c.argv.size()) { n=toLongOr(c.argv[i+1],10); i+=2; continue; }
        if (c.argv[i].startsWith("-") && c.argv[i].length()>1 && isdigit((unsigned char)c.argv[i][1])) {
            n = toLongOr(c.argv[i].substring(1), 10); ++i; continue;
        }
        ++i;
    }
    String all;
    for (; i<c.argv.size(); ++i) {
        Cmd cc=c; cc.argv.clear(); cc.argv.push_back("cat"); cc.argv.push_back(c.argv[i]);
        cc.exe="cat"; all += cmdCat_(cc);
    }
    if (!all.length()) return all;
    // split & cap
    std::vector<String> lines;
    int start=0;
    for (int k=0;k<(int)all.length();++k) if (all[k]=='\n') { lines.push_back(all.substring(start,k)); start=k+1; }
    if (start<(int)all.length()) lines.push_back(all.substring(start));
    String r;
    if (!tail) {
        for (int k=0;k<min((int)lines.size(),n);++k) { r+=lines[k]; r+="\n"; }
    } else {
        int s = max(0, (int)lines.size()-n);
        for (int k=s;k<(int)lines.size();++k) { r+=lines[k]; r+="\n"; }
    }
    return r;
}

String FakeShell::cmdGrep_(Cmd& c) {
    if (c.argv.size()<3) return "";
    String pat;
    size_t i=1;
    while (i<c.argv.size() && c.argv[i].startsWith("-")) ++i;
    if (i>=c.argv.size()) return "";
    pat = c.argv[i++]; pat.toLowerCase();
    String r;
    for (;i<c.argv.size();++i) {
        Cmd cc; cc.argv.push_back("cat"); cc.argv.push_back(c.argv[i]); cc.exe="cat";
        String body = cmdCat_(cc);
        int s=0;
        for (int k=0;k<(int)body.length();++k) {
            if (body[k]=='\n') {
                String ln = body.substring(s,k); String low=ln; low.toLowerCase();
                if (low.indexOf(pat)>=0) { r+=ln; r+='\n'; }
                s=k+1;
            }
        }
    }
    if (!r.length()) last_status_ok_=false;
    return r;
}

String FakeShell::cmdWc_(Cmd& c) {
    if (c.argv.size()<2) return "";
    String r;
    for (size_t i=1;i<c.argv.size();++i) {
        if (c.argv[i].startsWith("-")) continue;
        Cmd cc; cc.argv.push_back("cat"); cc.argv.push_back(c.argv[i]); cc.exe="cat";
        String body = cmdCat_(cc);
        int lines=0, words=0, bytes=body.length();
        for (int k=0;k<(int)body.length();++k) if (body[k]=='\n') ++lines;
        bool inw=false;
        for (int k=0;k<(int)body.length();++k) {
            bool sp=isspace((unsigned char)body[k]);
            if (!sp && !inw) { ++words; inw=true; }
            if (sp) inw=false;
        }
        char buf[64]; snprintf(buf,sizeof(buf),"%d %d %d ", lines, words, bytes);
        r += buf; r += c.argv[i]; r += '\n';
    }
    return r;
}

String FakeShell::cmdBase64_(Cmd& c) {
    bool dec=false;
    for (auto& a : c.argv) if (a=="-d"||a=="--decode") dec=true;
    if (dec) return "";
    return "";
}

String FakeShell::cmdUname_(Cmd& c) {
    bool a=false,s=false,r=false,m=false,n=false,p=false,o=false;
    if (c.argv.size()<2) s=true;
    for (size_t i=1;i<c.argv.size();++i) {
        const String& x=c.argv[i];
        if (x=="-a") a=true;
        else if (x=="-s") s=true;
        else if (x=="-r") r=true;
        else if (x=="-m") m=true;
        else if (x=="-n") n=true;
        else if (x=="-p") p=true;
        else if (x=="-o") o=true;
    }
    if (a) return String(FAKE_UNAME_A)+"\n";
    String out;
    if (s) out += "Linux";
    if (n) { if (out.length()) out+=' '; out+=host_; }
    if (r) { if (out.length()) out+=' '; out+="4.15.0-142-generic"; }
    if (m) { if (out.length()) out+=' '; out+="x86_64"; }
    if (p) { if (out.length()) out+=' '; out+="x86_64"; }
    if (o) { if (out.length()) out+=' '; out+="GNU/Linux"; }
    out+="\n"; return out;
}

String FakeShell::cmdId_(Cmd& c) {
    String t = (c.argv.size()>=2 && !c.argv[1].startsWith("-")) ? c.argv[1] : user_;
    if (t=="root") return "uid=0(root) gid=0(root) groups=0(root)\n";
    return "uid=1000(" + t + ") gid=1000(" + t + ") groups=1000(" + t + "),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),116(lxd)\n";
}

String FakeShell::cmdPs_(Cmd& c) {
    bool aux=false, ef=false;
    for (auto& a : c.argv) {
        if (a.indexOf('a')>=0 && a.indexOf('u')>=0 && a.indexOf('x')>=0) aux=true;
        if (a=="-ef"||a=="ef") ef=true;
    }
    String out;
    if (aux) {
        out += "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND\n";
        for (auto& p : procs_) {
            char buf[256];
            snprintf(buf,sizeof(buf),"%-10s %5u  0.0  0.1  %6u  %4u %-8s Ss   09:14   0:00 ",
                     p.user.c_str(), p.pid, p.vsz, p.rss, p.tty.c_str());
            out += buf; out += p.cmd; out += "\n";
        }
    } else if (ef) {
        out += "UID        PID  PPID  C STIME TTY          TIME CMD\n";
        for (auto& p : procs_) {
            char buf[256];
            snprintf(buf,sizeof(buf),"%-10s %5u %5u  0 09:14 %-12s 00:00:00 ",
                     p.user.c_str(), p.pid, (unsigned)1, p.tty.c_str());
            out += buf; out += p.cmd; out += "\n";
        }
    } else {
        out += "  PID TTY          TIME CMD\n";
        for (auto& p : procs_) if (p.tty.startsWith("pts")||p.tty=="tty1") {
            char buf[64]; snprintf(buf,sizeof(buf),"%5u %-12s 00:00:00 ",p.pid,p.tty.c_str());
            out += buf; out += p.cmd; out += "\n";
        }
    }
    return out;
}

String FakeShell::cmdNetstat_(Cmd& c) {
    (void)c;
    return
        "Active Internet connections (servers and established)\n"
        "Proto Recv-Q Send-Q Local Address           Foreign Address         State\n"
        "tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN\n"
        "tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN\n"
        "tcp        0      0 10.0.0.42:22            "+src_ip_+":"+String(src_port_)+"          ESTABLISHED\n"
        "tcp6       0      0 :::22                   :::*                    LISTEN\n";
}

String FakeShell::cmdSs_(Cmd& c) { return cmdNetstat_(c); }

String FakeShell::cmdIfconfig_(Cmd& c) {
    (void)c;
    return
        "eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500\n"
        "        inet 10.0.0.42  netmask 255.255.255.0  broadcast 10.0.0.255\n"
        "        inet6 fe80::216:3eff:fe0a:b1c2  prefixlen 64  scopeid 0x20<link>\n"
        "        ether 00:16:3e:0a:b1:c2  txqueuelen 1000  (Ethernet)\n"
        "        RX packets 18234  bytes 21438211 (21.4 MB)\n"
        "        TX packets 11201  bytes 1733122 (1.7 MB)\n\n"
        "lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536\n"
        "        inet 127.0.0.1  netmask 255.0.0.0\n"
        "        inet6 ::1  prefixlen 128  scopeid 0x10<host>\n"
        "        loop  txqueuelen 1000  (Local Loopback)\n";
}

String FakeShell::cmdIp_(Cmd& c) {
    if (c.argv.size()>=2 && (c.argv[1]=="a"||c.argv[1]=="addr"||c.argv[1]=="address")) {
        return
        "1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000\n"
        "    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00\n"
        "    inet 127.0.0.1/8 scope host lo\n"
        "       valid_lft forever preferred_lft forever\n"
        "2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000\n"
        "    link/ether 00:16:3e:0a:b1:c2 brd ff:ff:ff:ff:ff:ff\n"
        "    inet 10.0.0.42/24 brd 10.0.0.255 scope global eth0\n"
        "       valid_lft forever preferred_lft forever\n";
    }
    if (c.argv.size()>=2 && (c.argv[1]=="r"||c.argv[1]=="route")) return cmdRoute_(c);
    return "";
}

String FakeShell::cmdRoute_(Cmd& c) {
    (void)c;
    return
        "Kernel IP routing table\n"
        "Destination     Gateway         Genmask         Flags Metric Ref    Use Iface\n"
        "0.0.0.0         10.0.0.1        0.0.0.0         UG    100    0        0 eth0\n"
        "10.0.0.0        0.0.0.0         255.255.255.0   U     100    0        0 eth0\n";
}

String FakeShell::cmdDf_(Cmd& c) {
    bool h=false; for (auto& a : c.argv) if (a=="-h"||a=="-Th") h=true;
    if (h) return
        "Filesystem      Size  Used Avail Use% Mounted on\n"
        "udev            483M     0  483M   0% /dev\n"
        "tmpfs            99M  6.6M   92M   7% /run\n"
        "/dev/vda1        20G  4.7G   15G  24% /\n"
        "tmpfs           493M     0  493M   0% /dev/shm\n"
        "tmpfs           5.0M     0  5.0M   0% /run/lock\n"
        "tmpfs           493M     0  493M   0% /sys/fs/cgroup\n"
        "tmpfs            99M     0   99M   0% /run/user/0\n";
    return
        "Filesystem     1K-blocks    Used Available Use% Mounted on\n"
        "udev              494056       0    494056   0% /dev\n"
        "tmpfs             101000    6792     94208   7% /run\n"
        "/dev/vda1       20511356 4901324  15593648  24% /\n";
}

String FakeShell::cmdFree_(Cmd& c) {
    bool h=false,m=false; for (auto& a : c.argv) { if (a=="-h") h=true; if (a=="-m") m=true; }
    if (h) return
        "              total        used        free      shared  buff/cache   available\n"
        "Mem:           986M        274M        117M        6.4M        595M        687M\n"
        "Swap:            0B          0B          0B\n";
    if (m) return
        "              total        used        free      shared  buff/cache   available\n"
        "Mem:            986         274         117           6         595         687\n"
        "Swap:             0           0           0\n";
    return
        "              total        used        free      shared  buff/cache   available\n"
        "Mem:        1009856      280144      120432        6604      609280      703616\n"
        "Swap:             0           0           0\n";
}

String FakeShell::cmdUptime_(Cmd& c) {
    (void)c;
    return " 09:14:21 up 14 days,  3:42,  1 user,  load average: 0.08, 0.03, 0.01\n";
}
String FakeShell::cmdW_(Cmd& c) {
    (void)c;
    return
        " 09:14:21 up 14 days,  3:42,  1 user,  load average: 0.08, 0.03, 0.01\n"
        "USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT\n"
        "root     pts/0    "+pad(src_ip_,15)+"  09:14    0.00s  0.04s  0.00s -bash\n";
}
String FakeShell::cmdLast_(Cmd& c) {
    (void)c;
    return
        "root     pts/0        "+src_ip_+"     Mon Sep  4 09:14   still logged in\n"
        "root     pts/0        10.0.0.5         Sun Sep  3 22:01 - 22:43  (00:42)\n"
        "reboot   system boot  4.15.0-142-gener Sun Aug 20 09:32   still running\n\n"
        "wtmp begins Sun Aug 20 09:32:14 2023\n";
}
String FakeShell::cmdMount_(Cmd& c) { (void)c; return FAKE_MOUNTS_PROC; }
String FakeShell::cmdLscpu_(Cmd& c) {
    (void)c;
    return
        "Architecture:        x86_64\n"
        "CPU op-mode(s):      32-bit, 64-bit\n"
        "Byte Order:          Little Endian\n"
        "CPU(s):              1\n"
        "On-line CPU(s) list: 0\n"
        "Thread(s) per core:  1\n"
        "Core(s) per socket:  1\n"
        "Socket(s):           1\n"
        "Vendor ID:           GenuineIntel\n"
        "CPU family:          6\n"
        "Model:               79\n"
        "Model name:          Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz\n"
        "Stepping:            1\n"
        "CPU MHz:             2399.998\n"
        "BogoMIPS:            4799.99\n"
        "Hypervisor vendor:   KVM\n"
        "Virtualization type: full\n";
}

String FakeShell::cmdEnv_(Cmd& c) {
    (void)c;
    String r;
    for (auto& kv : env_) { r+=kv.first; r+='='; r+=kv.second; r+='\n'; }
    return r;
}
String FakeShell::cmdExport_(Cmd& c) {
    if (c.argv.size()<2) return cmdEnv_(c);
    for (size_t i=1;i<c.argv.size();++i) {
        int eq = c.argv[i].indexOf('=');
        if (eq>0) {
            String k=c.argv[i].substring(0,eq), v=c.argv[i].substring(eq+1);
            bool found=false;
            for (auto& kv : env_) if (kv.first==k) { kv.second=v; found=true; break; }
            if (!found) env_.push_back({k,v});
        }
    }
    return "";
}
String FakeShell::cmdHistory_(Cmd& c) {
    (void)c;
    String r;
    for (size_t i=0;i<history_.size();++i) {
        char buf[16]; snprintf(buf,sizeof(buf),"%5u  ",(unsigned)(i+1));
        r+=buf; r+=history_[i]; r+='\n';
    }
    return r;
}

// ----- wget/curl -----

static String parseDownloadUrl(const std::vector<String>& argv, String& outFile, bool& silent) {
    String url, file; silent=false;
    for (size_t i=1;i<argv.size();++i) {
        const String& a=argv[i];
        if (a=="-O" || a=="-o" || a=="--output-document" || a=="--output") {
            if (i+1<argv.size()) { file = argv[i+1]; ++i; }
            continue;
        }
        if (a.startsWith("-O")) { file=a.substring(2); continue; }
        if (a=="-q"||a=="--quiet"||a=="-s"||a=="--silent") { silent=true; continue; }
        if (a=="-fsSL"||a=="-sSL"||a=="-Lf"||a=="-fSL") { silent=true; continue; }
        if (a.startsWith("-")) continue;
        if (a.startsWith("http://")||a.startsWith("https://")||a.startsWith("ftp://")||a.startsWith("tftp://")) {
            url = a;
        }
    }
    if (!file.length() && url.length()) {
        int s = url.lastIndexOf('/');
        file = (s>=0) ? url.substring(s+1) : url;
        if (!file.length()) file = "index.html";
    }
    outFile = file;
    return url;
}

String FakeShell::cmdWget_(Cmd& c) {
    String file; bool silent=false;
    String url = parseDownloadUrl(c.argv, file, silent);
    if (!url.length()) {
        last_status_ok_=false;
        return "wget: missing URL\nUsage: wget [OPTION]... [URL]...\n";
    }
    String dst = file.startsWith("/") ? file : (cwd_+"/"+file);
    String abs = resolvePath_(dst);
    String dir = abs.substring(0, abs.lastIndexOf('/')+1);
    if (!isWritableDir_(dir)) abs = "/tmp/" + basename_(file);
    VirtualFile* vf = createFile_(abs, "wget");
    String arch = guessArch_(url+" "+file);
    String prof = guessProfile_(url, file);
    if (vf) {
        vf->source_url = url;
        vf->arch = arch;
        vf->payload_profile = prof;
        vf->size = 8192 + (millis() & 0xfff);
        vf->mode = 0644;
        vf->mtime_ms = millis();
    }
    StaticJsonDocument<384> d;
    d["url"]=url; d["file"]=abs; d["tool"]="wget";
    d["arch"]=arch; d["profile"]=prof;
    String body; serializeJson(d, body);
    logEvent_("download_url", body);

    if (silent) return "";
    String r;
    r += "--"; r += "2023-09-04 09:14:21--  "; r += url; r += "\n";
    int slashslash = url.indexOf("//");
    String host = (slashslash>=0) ? url.substring(slashslash+2) : url;
    int sl = host.indexOf('/'); if (sl>0) host = host.substring(0,sl);
    r += "Resolving "+host+" ("+host+")... 185.199.108.133\n";
    r += "Connecting to "+host+" ("+host+")|185.199.108.133|:80... connected.\n";
    r += "HTTP request sent, awaiting response... 200 OK\n";
    r += "Length: "+String(vf?vf->size:8192)+" (8.0K) [application/octet-stream]\n";
    r += "Saving to: '"+basename_(abs)+"'\n\n";
    r += basename_(abs)+"     100%[===================>]   8.00K  --.-KB/s    in 0s\n\n";
    r += "2023-09-04 09:14:21 (12.4 MB/s) - '"+basename_(abs)+"' saved ["+String(vf?vf->size:8192)+"/"+String(vf?vf->size:8192)+"]\n\n";
    return r;
}

String FakeShell::cmdCurl_(Cmd& c) {
    String file; bool silent=false;
    String url = parseDownloadUrl(c.argv, file, silent);
    if (!url.length()) { last_status_ok_=false; return "curl: try 'curl --help' for more information\n"; }
    bool to_stdout = true;
    for (size_t i=1;i<c.argv.size();++i) if (c.argv[i]=="-o"||c.argv[i]=="-O"||c.argv[i].startsWith("-O")) to_stdout=false;
    String abs;
    if (!to_stdout) {
        String dst = file.startsWith("/") ? file : (cwd_+"/"+file);
        abs = resolvePath_(dst);
        String dir = abs.substring(0, abs.lastIndexOf('/')+1);
        if (!isWritableDir_(dir)) abs = "/tmp/" + basename_(file);
        VirtualFile* vf = createFile_(abs, "curl");
        if (vf) {
            vf->source_url = url;
            vf->arch = guessArch_(url+" "+file);
            vf->payload_profile = guessProfile_(url, file);
            vf->size = 8192 + (millis() & 0xfff);
        }
    }
    StaticJsonDocument<384> d;
    d["url"]=url; d["file"]=abs.length()?abs:String("-");
    d["tool"]="curl"; d["arch"]=guessArch_(url+" "+file); d["profile"]=guessProfile_(url, file);
    String body; serializeJson(d, body);
    logEvent_("download_url", body);

    if (silent) return "";
    if (!to_stdout) return "";
    // print fake script content if URL ends in .sh — keeps "curl ... | sh" attackers engaged
    String low = url; low.toLowerCase();
    if (low.endsWith(".sh")) {
        return "#!/bin/sh\n# fake remote script\nexit 0\n";
    }
    return "";
}

// ----- chmod/chown/rm/mkdir/touch/mv/cp -----

String FakeShell::cmdChmod_(Cmd& c) {
    if (c.argv.size()<3) return "";
    String mode = c.argv[1];
    bool exec = (mode.indexOf("+x")>=0||mode.indexOf("a+x")>=0||mode.indexOf("u+x")>=0||
                 mode=="755"||mode=="0755"||mode=="777"||mode=="0777"||mode=="700"||mode=="0700"||mode=="555");
    for (size_t i=2;i<c.argv.size();++i) {
        String abs = resolvePath_(c.argv[i]);
        VirtualFile* vf = findFile_(abs);
        if (!vf) vf = createFile_(abs, "chmod");
        if (vf) { vf->executable = exec ? true : vf->executable; vf->mode = (uint16_t)toLongOr(mode,0644); }
        StaticJsonDocument<256> d;
        d["path"]=abs; d["mode"]=mode; d["executable"]=exec;
        String body; serializeJson(d,body);
        logEvent_("chmod", body);
    }
    return "";
}
String FakeShell::cmdChown_(Cmd& c) { (void)c; return ""; }
String FakeShell::cmdRm_(Cmd& c) {
    for (size_t i=1;i<c.argv.size();++i) {
        if (c.argv[i].startsWith("-")) continue;
        String abs = resolvePath_(c.argv[i]);
        for (auto it = files_.begin(); it != files_.end(); ) {
            if (it->path == abs || it->path.startsWith(abs+"/")) it = files_.erase(it);
            else ++it;
        }
    }
    return "";
}
String FakeShell::cmdMkdir_(Cmd& c) {
    for (size_t i=1;i<c.argv.size();++i) {
        if (c.argv[i].startsWith("-")) continue;
        String abs = resolvePath_(c.argv[i]);
        VirtualFile* vf = createFile_(abs, "mkdir");
        if (vf) { vf->is_dir=true; vf->mode=0755; }
    }
    return "";
}
String FakeShell::cmdTouch_(Cmd& c) {
    for (size_t i=1;i<c.argv.size();++i) {
        if (c.argv[i].startsWith("-")) continue;
        String abs = resolvePath_(c.argv[i]);
        VirtualFile* vf = createFile_(abs, "touch");
        if (vf) vf->mtime_ms = millis();
    }
    return "";
}
String FakeShell::cmdMv_(Cmd& c) {
    if (c.argv.size()<3) return "";
    String src = resolvePath_(c.argv[1]);
    String dst = resolvePath_(c.argv[2]);
    auto* sf = findFile_(src);
    if (sf) sf->path = dst;
    return "";
}
String FakeShell::cmdCp_(Cmd& c) {
    if (c.argv.size()<3) return "";
    String src = resolvePath_(c.argv[c.argv.size()-2]);
    String dst = resolvePath_(c.argv[c.argv.size()-1]);
    auto* sf = findFile_(src);
    if (sf) {
        VirtualFile nf = *sf; nf.path = dst; nf.created_by="cp";
        if (files_.size() < MAX_VFS_FILES) files_.push_back(nf);
    }
    return "";
}

String FakeShell::cmdWhich_(Cmd& c) {
    String r;
    for (size_t i=1;i<c.argv.size();++i) {
        const String& n = c.argv[i];
        if (n=="ls"||n=="cat"||n=="echo"||n=="rm"||n=="cp"||n=="mv"||n=="chmod"||
            n=="bash"||n=="sh"||n=="ps"||n=="grep"||n=="head"||n=="tail")
            r += "/bin/"+n+"\n";
        else if (n=="wget"||n=="curl"||n=="python"||n=="python3"||n=="perl"||n=="php"||
                 n=="nc"||n=="ncat"||n=="ifconfig"||n=="ip"||n=="ss"||n=="netstat"||
                 n=="apt"||n=="apt-get"||n=="dpkg")
            r += "/usr/bin/"+n+"\n";
        else { last_status_ok_=false; }
    }
    return r;
}
String FakeShell::cmdWhereis_(Cmd& c) {
    String r;
    for (size_t i=1;i<c.argv.size();++i) {
        if (c.argv[i].startsWith("-")) continue;
        r += c.argv[i] + ": /usr/bin/" + c.argv[i] + " /usr/share/man/man1/" + c.argv[i] + ".1.gz\n";
    }
    return r;
}

String FakeShell::cmdSleep_(Cmd& c) {
    if (c.argv.size()<2) return "";
    long ms;
    String s = c.argv[1];
    if (s.endsWith("s")) { ms = toLongOr(s.substring(0,s.length()-1), 1) * 1000; }
    else if (s.endsWith("m")) { ms = toLongOr(s.substring(0,s.length()-1), 1) * 60000; }
    else { ms = toLongOr(s, 1) * 1000; }
    StaticJsonDocument<128> d;
    d["requested_ms"] = (uint32_t)ms;
    String body; serializeJson(d, body);
    logEvent_("sleep", body);
    if (ms < 0) ms = 0;
    if ((uint32_t)ms > MAX_SLEEP_MS) ms = MAX_SLEEP_MS;
    delay(ms);
    return "";
}

// ----- apt/dpkg/pip -----

String FakeShell::cmdApt_(Cmd& c) {
    String sub = (c.argv.size()>=2) ? c.argv[1] : "";
    if (sub=="update") {
        return
        "Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease\n"
        "Hit:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease\n"
        "Hit:3 http://archive.ubuntu.com/ubuntu bionic-backports InRelease\n"
        "Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease\n"
        "Reading package lists... Done\n";
    }
    if (sub=="install"||sub=="-y"||sub=="reinstall") {
        StaticJsonDocument<256> d;
        JsonArray a = d["pkgs"].to<JsonArray>();
        for (size_t i=2;i<c.argv.size();++i) if (!c.argv[i].startsWith("-")) a.add(c.argv[i]);
        String body; serializeJson(d, body);
        logEvent_("package_install_attempt", body);
        return
        "Reading package lists... Done\n"
        "Building dependency tree\n"
        "Reading state information... Done\n"
        "E: Unable to locate package "+(c.argv.size()>=3?c.argv[2]:String("?"))+"\n";
    }
    if (sub=="remove"||sub=="purge") return "Reading package lists... Done\nBuilding dependency tree\n";
    if (sub=="list") return "Listing... Done\n";
    if (sub=="upgrade") return "Reading package lists... Done\n0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.\n";
    return "";
}
String FakeShell::cmdDpkg_(Cmd& c) {
    if (c.argv.size()>=2 && (c.argv[1]=="-l"||c.argv[1]=="--list")) {
        return
        "Desired=Unknown/Install/Remove/Purge/Hold\n"
        "| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend\n"
        "|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)\n"
        "||/ Name           Version          Architecture     Description\n"
        "+++-==============-================-================-====================\n"
        "ii  bash           4.4.18-2ubuntu1  amd64            GNU Bourne Again SHell\n"
        "ii  coreutils      8.28-1ubuntu1    amd64            GNU core utilities\n"
        "ii  openssh-server 1:7.6p1-4        amd64            secure shell server\n";
    }
    return "";
}
String FakeShell::cmdPip_(Cmd& c) {
    if (c.argv.size()>=2 && c.argv[1]=="install") {
        StaticJsonDocument<256> d;
        JsonArray a = d["pkgs"].to<JsonArray>();
        for (size_t i=2;i<c.argv.size();++i) if (!c.argv[i].startsWith("-")) a.add(c.argv[i]);
        String body; serializeJson(d, body);
        logEvent_("pip_install_attempt", body);
        return "Collecting "+String(c.argv.size()>=3?c.argv[2]:"")+"\nERROR: Could not find a version that satisfies the requirement\n";
    }
    return "";
}

// ----- crontab/systemctl/service -----

String FakeShell::cmdCrontab_(Cmd& c) {
    if (c.argv.size()>=2 && c.argv[1]=="-l") return crontab_;
    if (c.argv.size()>=2 && c.argv[1]=="-r") { crontab_=""; return ""; }
    if (c.argv.size()>=2 && c.argv[1]=="-e") return ""; // editor not real
    // crontab <file> form — read into our crontab
    if (c.argv.size()>=2 && !c.argv[1].startsWith("-")) {
        String abs = resolvePath_(c.argv[1]);
        auto* vf = findFile_(abs);
        if (vf) {
            crontab_ = vf->content;
            StaticJsonDocument<256> d;
            d["from"]=abs; d["bytes"]=(uint32_t)crontab_.length();
            String body; serializeJson(d,body);
            logEvent_("cron_modified", body);
        }
    }
    return "";
}
String FakeShell::cmdSystemctl_(Cmd& c) {
    if (c.argv.size()>=2 && (c.argv[1]=="enable"||c.argv[1]=="start"||c.argv[1]=="restart")) {
        StaticJsonDocument<256> d;
        d["action"]=c.argv[1];
        d["unit"]=(c.argv.size()>=3?c.argv[2]:String(""));
        String body; serializeJson(d,body);
        logEvent_("systemd_service_modified", body);
        return "";
    }
    if (c.argv.size()>=2 && c.argv[1]=="status") {
        return "● "+(c.argv.size()>=3?c.argv[2]:String("unit"))+" - service\n   Loaded: loaded\n   Active: active (running)\n";
    }
    return "";
}
String FakeShell::cmdService_(Cmd& c) { return cmdSystemctl_(c); }
String FakeShell::cmdKill_(Cmd& c, const String& which) { (void)c; (void)which; return ""; }

String FakeShell::cmdNc_(Cmd& c) {
    // log as recon/reverse-shell candidate; output nothing
    StaticJsonDocument<256> d;
    JsonArray a = d["argv"].to<JsonArray>();
    for (auto& x : c.argv) a.add(x);
    String body; serializeJson(d, body);
    logEvent_("nc_invoked", body);
    return "";
}
String FakeShell::cmdPing_(Cmd& c) {
    String tgt = (c.argv.size()>=2) ? c.argv[c.argv.size()-1] : "8.8.8.8";
    return "PING "+tgt+" ("+tgt+") 56(84) bytes of data.\n64 bytes from "+tgt+": icmp_seq=1 ttl=54 time=11.4 ms\n";
}
String FakeShell::cmdIptables_(Cmd& c) {
    if (c.argv.size()>=2 && c.argv[1]=="-L") {
        return
        "Chain INPUT (policy ACCEPT)\ntarget     prot opt source               destination\n\n"
        "Chain FORWARD (policy ACCEPT)\ntarget     prot opt source               destination\n\n"
        "Chain OUTPUT (policy ACCEPT)\ntarget     prot opt source               destination\n";
    }
    StaticJsonDocument<256> d;
    JsonArray a = d["argv"].to<JsonArray>();
    for (auto& x : c.argv) a.add(x);
    String body; serializeJson(d,body);
    logEvent_("iptables_change", body);
    return "";
}
String FakeShell::cmdUfw_(Cmd& c) {
    if (c.argv.size()>=2 && c.argv[1]=="status") return "Status: inactive\n";
    return "";
}

// ----- sh -c / interpreters / direct execution -----

String FakeShell::cmdShEval_(Cmd& c) {
    // sh / bash with no -c => acts as a recursive shell prompt; just no-op.
    int dashc = -1;
    for (size_t i=1;i<c.argv.size();++i) if (c.argv[i]=="-c") { dashc=(int)i; break; }
    if (dashc<0 || dashc+1>=(int)c.argv.size()) return "";
    String inner = c.argv[dashc+1];
    StaticJsonDocument<384> d;
    d["wrapper"]=c.exe;
    d["script"]=inner.substring(0, min((unsigned)inner.length(), 480u));
    String body; serializeJson(d,body);
    logEvent_("script_execution", body);
    // recurse — split & run inner chain (don't double-count toward command cap)
    if (commands_ < MAX_COMMANDS_PER_SESSION) {
        return runChain_(inner);
    }
    return "";
}

String FakeShell::cmdInterp_(Cmd& c) {
    String inner;
    for (size_t i=1;i<c.argv.size();++i) {
        if (c.argv[i]=="-c" && i+1<c.argv.size()) { inner = c.argv[i+1]; break; }
    }
    if (inner.length()) {
        StaticJsonDocument<384> d;
        d["interp"]=c.exe;
        d["script"]=inner.substring(0, min((unsigned)inner.length(), 480u));
        String body; serializeJson(d,body);
        logEvent_("script_execution", body);
        return "";
    }
    // python myscript.py — try to "run" the script if we have it
    if (c.argv.size()>=2 && !c.argv[1].startsWith("-")) {
        String abs = resolvePath_(c.argv[1]);
        auto* vf = findFile_(abs);
        if (vf) {
            StaticJsonDocument<256> d;
            d["interp"]=c.exe; d["file"]=abs; d["profile"]=vf->payload_profile;
            String body; serializeJson(d,body);
            logEvent_("script_execution", body);
        }
    }
    return "";
}

String FakeShell::cmdExecute_(Cmd& c) {
    String tgt = c.argv[0];
    String abs = resolvePath_(tgt);
    auto* vf = findFile_(abs);
    if (!vf) {
        last_status_ok_=false;
        return "-bash: " + tgt + ": No such file or directory\n";
    }
    if (!vf->executable) {
        last_status_ok_=false;
        return "-bash: " + tgt + ": Permission denied\n";
    }
    vf->executed = true; vf->exec_count++;
    StaticJsonDocument<384> d;
    d["file"]=abs; d["url"]=vf->source_url; d["arch"]=vf->arch;
    d["profile"]=vf->payload_profile; d["exec_count"]=vf->exec_count;
    String body; serializeJson(d,body);
    logEvent_("payload_execution", body);

    // Insert a fake process for ps
    if (procs_.size() < 64) {
        FakeProcess p;
        p.pid = 1000 + (millis() & 0x1fff);
        p.user = user_;
        p.tty = "?";
        p.cmd = abs;
        procs_.push_back(p);
    }

    // realistic small delay
    delay(min((uint32_t)1500, MAX_SLEEP_MS));
    return "";
}

String FakeShell::commandSummary(size_t max_bytes) const {
    String out;
    out.reserve(256);
    for (size_t i = 0; i < history_.size(); ++i) {
        if (out.length() + history_[i].length() + 1 > max_bytes) break;
        if (out.length()) out += '\n';
        out += history_[i];
    }
    return out;
}

} // namespace honeyopus
